[package]
name    = "gnitz-py"
version = "0.1.0"
edition = "2021"

[lib]
name       = "gnitz"
crate-type = ["cdylib"]

[features]
default     = []

[dependencies]
pyo3           = { version = "0.29", features = ["extension-module"] }
gnitz-core     = { path = "../gnitz-core" }
gnitz-expr     = { path = "../gnitz-expr" }
gnitz-mirror   = { path = "../gnitz-mirror" }
gnitz-sql      = { path = "../gnitz-sql" }
gnitz-wire     = { path = "../gnitz-wire" }

[lints]
workspace = true
