import asyncio
from collections.abc import Callable, Generator, Iterable, Iterator, Sequence
from types import GenericAlias
from typing import Any, Literal, Self, final, type_check_only

from typing_extensions import disjoint_base

from gnitz._types import SqlResult

# A delta cursor: `(tag, tick)`.
type _Cursor = tuple[int, int]
type _ConflictMode = Literal["update", "error"]

__all__ = [
    "ColumnDef",
    "Schema",
    "Row",
    "ZSetBatch",
    "ScanResult",
    "RowIterator",
    "_Client",
    "GnitzClient",
    "AsyncGnitzClient",
    "LoopCore",
    "Txn",
    "Pipeline",
    "Pending",
    "PollResult",
    "GnitzError",
    "GnitzRefusedError",
    "GnitzConnectionError",
    "GnitzConflictError",
    "GnitzDeltaExpiredError",
    "GnitzSalFullError",
    "GnitzMirrorPoisonedError",
    "GnitzNotFoundError",
    "GnitzIntegrityError",
    "SCHEMA_TAB",
    "TABLE_TAB",
    "COL_TAB",
    "IDX_TAB",
    "FIRST_USER_TABLE_ID",
    "MAX_COLUMNS",
    "debug_assertions",
    "type_codes",
    "instructions_retired",
    "sys_schema",
]

SCHEMA_TAB: int
TABLE_TAB: int
COL_TAB: int
IDX_TAB: int
FIRST_USER_TABLE_ID: int
MAX_COLUMNS: int
debug_assertions: bool

def sys_schema(table_id: int) -> Schema: ...
def type_codes() -> list[tuple[str, int]]: ...
def instructions_retired(f: Callable[[], object]) -> int: ...

class GnitzError(Exception): ...
class GnitzRefusedError(GnitzError): ...
class GnitzConnectionError(GnitzError): ...
class GnitzMirrorPoisonedError(GnitzError): ...
class GnitzConflictError(GnitzRefusedError): ...
class GnitzDeltaExpiredError(GnitzRefusedError): ...
class GnitzSalFullError(GnitzRefusedError): ...
class GnitzNotFoundError(GnitzRefusedError): ...
class GnitzIntegrityError(GnitzRefusedError): ...

# ---------------------------------------------------------------------------
# Schemas, batches and rows
# ---------------------------------------------------------------------------

@final
class ColumnDef:
    def __new__(
        cls, name: str, type_code: int, is_nullable: bool = False, is_hidden: bool = False, scale: int = 0
    ) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def type_code(self) -> int: ...
    @property
    def is_nullable(self) -> bool: ...
    @property
    def is_hidden(self) -> bool: ...
    @property
    def scale(self) -> int: ...

@final
class Schema:
    def __new__(cls, columns: Sequence[ColumnDef], pk_indices: Sequence[int]) -> Self: ...
    @property
    def columns(self) -> list[ColumnDef]: ...
    @property
    def pk_indices(self) -> list[int]: ...

@final
class ZSetBatch:
    def __new__(cls, schema: Schema) -> Self: ...
    def append(self, *, _weight: int = 1, **columns: Any) -> Self: ...
    def extend(self, rows: Iterable[dict[str, Any]], _weight: int = 1) -> Self: ...
    def rows(self) -> ScanResult: ...
    def __len__(self) -> int: ...

@disjoint_base
class Row:
    # The presented columns' names, and each one's key in `_asdict()` — `None`
    # where a later column of the same name takes it.
    _fields: tuple[str, ...]
    _keys: tuple[str | None, ...]
    @property
    def _weight(self) -> int: ...
    def __getitem__(self, key: int | str, /) -> Any: ...
    # A column, by name: a result's rows are of a `Row` subclass built for its
    # columns, which no stub can name.
    def __getattr__(self, name: str) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def _asdict(self) -> dict[str, Any]: ...

@final
class RowIterator:
    def __iter__(self) -> Self: ...
    def __next__(self) -> Row: ...

@final
class ScanResult:
    @property
    def lsn(self) -> int | None: ...
    @property
    def schema(self) -> Schema: ...
    def __iter__(self) -> RowIterator: ...
    def __len__(self) -> int: ...
    def including_hidden(self) -> ScanResult: ...

@final
class PollResult:
    @property
    def view_id(self) -> int: ...
    @property
    def reseeded(self) -> bool: ...
    @property
    def error(self) -> BaseException | None: ...
    @property
    def cursor(self) -> _Cursor | None: ...

# ---------------------------------------------------------------------------
# Clients
#
# Every verb is one method of the private base `_Client` at runtime, and what it returns is how
# its client waits: the result on a `GnitzClient`, a future of it on an
# `AsyncGnitzClient`, a `Pending` of it inside `GnitzClient.pipeline()`. A type
# cannot be abstracted over that, so each of the three spells the verbs out.
# ---------------------------------------------------------------------------

@disjoint_base
class _Client:
    schema: str
    def transaction(self) -> Txn[Self]: ...

@final
class GnitzClient(_Client):
    def __new__(cls, target: str, schema: str = "public") -> Self: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, _exc_type: object, _exc_val: object, _exc_tb: object) -> Literal[False]: ...
    def pipeline(self) -> Pipeline: ...
    @property
    def requests_sent(self) -> int: ...
    def create_schema(self, name: str) -> int: ...
    def drop_schema(self, name: str) -> None: ...
    def create_table(self, table_name: str, schema: Schema) -> int: ...
    def drop_table(self, table_name: str) -> None: ...
    def push(self, target_id: int, batch: ZSetBatch, mode: _ConflictMode = "update") -> int: ...
    def delete(self, target_id: int, schema: Schema, pks: Sequence[Any]) -> None: ...
    def create_view(self, view_name: str, source_name: str) -> int: ...
    def drop_view(self, view_name: str) -> None: ...
    def resolve_table(self, table_name: str) -> tuple[int, Schema]: ...
    def scan(self, target_id: int, schema: Schema) -> ScanResult: ...
    def delta_bootstrap(self, view_id: int, view_schema: Schema) -> tuple[ScanResult, _Cursor]: ...
    def delta_poll(
        self, view_id: int, view_schema: Schema, cursor: _Cursor, wait: float = 0.0
    ) -> tuple[ScanResult, _Cursor]: ...
    def scan_many(self, pairs: Sequence[tuple[int, Schema]]) -> list[ScanResult]: ...
    def seek(self, table_id: int, schema: Schema, pk: Any) -> ScanResult: ...
    def seek_by_index(
        self, table_id: int, schema: Schema, col_indices: Sequence[int], key_vals: list[Any]
    ) -> ScanResult: ...
    def execute_sql(self, sql: str) -> list[SqlResult]: ...
    def mirror_at(self, base_dir: str) -> None: ...
    def mirror_view(self, name: str) -> PollResult: ...
    def forget_view(self, view_id: int) -> None: ...
    def poll(self, wait: float = 0.0) -> list[PollResult]: ...
    def checkpoint(self) -> None: ...
    def close_mirror(self) -> None: ...
    def mirrored_ids(self) -> list[int]: ...
    def cursor(self, view_id: int) -> _Cursor | None: ...
    @property
    def mirror_poisoned(self) -> str | None: ...
    def reconnect(self, target: str) -> None: ...

@final
class AsyncGnitzClient(_Client):
    def __new__(cls, target: str, schema: str = "public") -> Self: ...
    def aclose(self) -> asyncio.Future[None]: ...
    def __aenter__(self) -> asyncio.Future[Self]: ...
    def __await__(self) -> Generator[Any, None, Self]: ...
    def __aexit__(self, _exc_type: object, _exc_val: object, _exc_tb: object) -> asyncio.Future[None]: ...
    @property
    def requests_sent(self) -> asyncio.Future[int]: ...
    def create_schema(self, name: str) -> asyncio.Future[int]: ...
    def drop_schema(self, name: str) -> asyncio.Future[None]: ...
    def create_table(self, table_name: str, schema: Schema) -> asyncio.Future[int]: ...
    def drop_table(self, table_name: str) -> asyncio.Future[None]: ...
    def push(self, target_id: int, batch: ZSetBatch, mode: _ConflictMode = "update") -> asyncio.Future[int]: ...
    def delete(self, target_id: int, schema: Schema, pks: Sequence[Any]) -> asyncio.Future[None]: ...
    def create_view(self, view_name: str, source_name: str) -> asyncio.Future[int]: ...
    def drop_view(self, view_name: str) -> asyncio.Future[None]: ...
    def resolve_table(self, table_name: str) -> asyncio.Future[tuple[int, Schema]]: ...
    def scan(self, target_id: int, schema: Schema) -> asyncio.Future[ScanResult]: ...
    def delta_bootstrap(self, view_id: int, view_schema: Schema) -> asyncio.Future[tuple[ScanResult, _Cursor]]: ...
    def delta_poll(
        self, view_id: int, view_schema: Schema, cursor: _Cursor, wait: float = 0.0
    ) -> asyncio.Future[tuple[ScanResult, _Cursor]]: ...
    def scan_many(self, pairs: Sequence[tuple[int, Schema]]) -> asyncio.Future[list[ScanResult]]: ...
    def seek(self, table_id: int, schema: Schema, pk: Any) -> asyncio.Future[ScanResult]: ...
    def seek_by_index(
        self, table_id: int, schema: Schema, col_indices: Sequence[int], key_vals: list[Any]
    ) -> asyncio.Future[ScanResult]: ...
    def execute_sql(self, sql: str) -> asyncio.Future[list[SqlResult]]: ...
    def mirror_at(self, base_dir: str) -> asyncio.Future[None]: ...
    def mirror_view(self, name: str) -> asyncio.Future[PollResult]: ...
    def forget_view(self, view_id: int) -> asyncio.Future[None]: ...
    def poll(self, wait: float = 0.0) -> asyncio.Future[list[PollResult]]: ...
    def checkpoint(self) -> asyncio.Future[None]: ...
    def close_mirror(self) -> asyncio.Future[None]: ...
    def mirrored_ids(self) -> asyncio.Future[list[int]]: ...
    def cursor(self, view_id: int) -> asyncio.Future[_Cursor | None]: ...
    @property
    def mirror_poisoned(self) -> asyncio.Future[str | None]: ...
    def reconnect(self, target: str) -> asyncio.Future[None]: ...

# What `Pipeline.__enter__` returns. It is the `GnitzClient` itself, whose verbs
# return a `Pending` for as long as the block is open — so the block's calls are
# typed only when made through the name `with ... as` binds.
@final
@type_check_only
class _PipelinedClient:
    schema: str
    def transaction(self) -> Txn[Self]: ...
    @property
    def requests_sent(self) -> int: ...
    def create_schema(self, name: str) -> Pending[int]: ...
    def drop_schema(self, name: str) -> Pending[None]: ...
    def create_table(self, table_name: str, schema: Schema) -> Pending[int]: ...
    def drop_table(self, table_name: str) -> Pending[None]: ...
    def push(self, target_id: int, batch: ZSetBatch, mode: _ConflictMode = "update") -> Pending[int]: ...
    def delete(self, target_id: int, schema: Schema, pks: Sequence[Any]) -> Pending[None]: ...
    def create_view(self, view_name: str, source_name: str) -> Pending[int]: ...
    def drop_view(self, view_name: str) -> Pending[None]: ...
    def resolve_table(self, table_name: str) -> Pending[tuple[int, Schema]]: ...
    def scan(self, target_id: int, schema: Schema) -> Pending[ScanResult]: ...
    def delta_bootstrap(self, view_id: int, view_schema: Schema) -> Pending[tuple[ScanResult, _Cursor]]: ...
    def delta_poll(
        self, view_id: int, view_schema: Schema, cursor: _Cursor, wait: float = 0.0
    ) -> Pending[tuple[ScanResult, _Cursor]]: ...
    def scan_many(self, pairs: Sequence[tuple[int, Schema]]) -> Pending[list[ScanResult]]: ...
    def seek(self, table_id: int, schema: Schema, pk: Any) -> Pending[ScanResult]: ...
    def seek_by_index(
        self, table_id: int, schema: Schema, col_indices: Sequence[int], key_vals: list[Any]
    ) -> Pending[ScanResult]: ...
    def execute_sql(self, sql: str) -> Pending[list[SqlResult]]: ...
    def mirror_at(self, base_dir: str) -> Pending[None]: ...
    def mirror_view(self, name: str) -> Pending[PollResult]: ...
    def forget_view(self, view_id: int) -> Pending[None]: ...
    def poll(self, wait: float = 0.0) -> Pending[list[PollResult]]: ...
    def checkpoint(self) -> Pending[None]: ...
    def close_mirror(self) -> Pending[None]: ...
    def mirrored_ids(self) -> list[int]: ...
    def cursor(self, view_id: int) -> _Cursor | None: ...
    @property
    def mirror_poisoned(self) -> str | None: ...
    def reconnect(self, target: str) -> Pending[None]: ...

@final
class Pending[T]:
    def result(self) -> T: ...
    def __class_getitem__(cls, key: Any) -> GenericAlias: ...

@final
class Pipeline:
    def __enter__(self) -> _PipelinedClient: ...
    def __exit__(self, exc_type: object, _exc_val: object, _exc_tb: object) -> Literal[False]: ...

# Entered with `with` on a client that blocks, `async with` on one that awaits.
@final
class Txn[ClientT]:
    def __class_getitem__(cls, key: Any) -> GenericAlias: ...
    def __enter__(self: Txn[GnitzClient] | Txn[_PipelinedClient]) -> ClientT: ...
    def __exit__(
        self: Txn[GnitzClient] | Txn[_PipelinedClient], exc_type: object, _exc_val: object, _exc_tb: object
    ) -> Literal[False]: ...
    def __aenter__(self: Txn[AsyncGnitzClient]) -> asyncio.Future[ClientT]: ...
    def __aexit__(
        self: Txn[AsyncGnitzClient], exc_type: object, _exc_val: object, _exc_tb: object
    ) -> asyncio.Future[Literal[False]]: ...

# The event-loop side of an `AsyncGnitzClient`, whose methods are the loop's callbacks.
@final
class LoopCore:
    def on_readable(self) -> None: ...
    def on_writable(self) -> None: ...
    def on_flush(self) -> None: ...
